version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - '4000:4000'
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: frontend_c
    ports:
      - '3000:3000'
    stdin_open: true
    
  postgres:
    image: postgres:14.1-alpine
    restart: always
    container_name: postgress_c
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=test_db
    ports:
      - "5432:5432"
    volumes:
      - postgres:/data/postgres
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_c
    image: dpage/pgadmin4
    environment: 
      - PGADMIN_DEFAULT_EMAIL=vlada@test.com
      - PGADMIN_DEFAULT_PASSWORD=test
    restart: always
    ports:
      - '5050:80'
    volumes: 
      - pgadmin:/var/lib/pgadmin
    networks:
      - postgres

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: